version: '3'
services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: "always"
    ports:
      - "1880:1880" # Porta padrão do Node-RED
    environment:
      - NODE_RED_ENABLE_PROJECTS=true
    volumes:
      - ~/.node-red/data:/data # Volume montado para persistência de dados
    mem_limit: 512m
    user: "0:0" # UID e GID do usuário 'pi'
