version: '3'
services:
  node-red:
    image: nodered/node-red:latest  # Use an appropriate tag for the ARM architecture of the Raspberry Pi
    container_name: node-red
    restart: always
    user: "root"                    # Run the container as root
    ports:
      - "1880:1880"                 # Default Node-RED port
    volumes:
      - ~/.node-red/data:/data      # Ensures data persistence across container restarts
                                    